Fix Zalozky page - add missing useTranslation hook to BookmarkTableCard
Error: t is not defined at line 148
Solution: Added const { t } = useTranslation() to BookmarkTableCard component